bearer_token_dns = "REPLACE_WITH_CLOUDFLARE_BEARER_TOKEN"
zone_id = "REPLACE_WITH_CLOUDFLARE_DOMAIN_ID"
account_id = "REPLACE_WITH_CLOUDFLARE_ACCOUNT_ID"
domain_name= "REPLACE_WITH_CLOUDFLARE_DOMAIN_NAME"

